matrix:
  include:
    - language: java
      jdk: openjdk8
      before_script:
        - cd Robot
      script:
        - ./gradlew build

    - language: rust
      cache: cargo
      rust: stable
      before_script:
        - cd Vision
      script:
        - cargo test

cache:
  directories:
    - $OPENCV_INSTALL_DIR
  pip: true
env:
  global:
    - OPENCV_VERSION=3.2.0
    - OPENCV_INSTALL_DIR="$HOME/opencv-$OPENCV_VERSION-install"
    - LD_LIBRARY_PATH="$OPENCV_INSTALL_DIR/lib"
    - PKG_CONFIG_PATH="$OPENCV_INSTALL_DIR/lib/pkgconfig"
    - PYTHONPATH="$OPENCV_INSTALL_DIR/lib/python3.6/site-packages"
install:
- chmod +x ./opencv_install.sh && ./opencv_install.sh