matrix:
  include:
    - language: java
      jdk: openjdk8
      before_script:
        - cd Robot
      script:
        - ./gradlew build

    - language: rust
      cache: cargo
      cache:
        timeout: 1000
        cargo: true
        directories:
          - $HOME/usr/installed-version
          - $HOME/usr/include
          - $HOME/usr/lib
      env:
        global:
          - MAKEFLAGS="-j 4"
      sudo: required
      dist: trusty
      before_install:
      - chmod +x ./opencv_install.sh && sudo -E ./opencv_install.sh
      - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib/x86_64-linux-gnu
      addons:
        apt:
          packages:
          - build-essential
          - cmake
          - git
          - libavcodec-dev
          - libavformat-dev
          - libdc1394-22-dev
          - libgmp-dev
          - libgtk2.0-dev
          - libjasper-dev
          - libjpeg-dev
          - libleptonica-dev
          - libpng-dev
          - libswscale-dev
          - libtbb-dev
          - libtbb2
          - libtiff-dev
          - pkg-config
          - xvfb
      rust: stable
      before_script:
        - cd Vision
      script:
        - cargo test