matrix:
  include:
    - language: java
      jdk: openjdk8
      before_script:
        - cd Robot
      script:
        - ./gradlew build

    - language: rust
      addons:
        apt:
          sources:
            - sourceline: 'ppa:orangain/opencv'
          packages:
            - opencv
      cache: cargo
      rust: stable
      before_script:
        - cd Vision
      script:
        - cargo test
