[package]
name = "Vision"
version = "0.1.0"
authors = ["Conner Ebbinghaus <connerebbinghaus@gmail.com>"]

[dependencies]
cv = { git = "https://github.com/nebgnahz/cv-rs.git" }
mqtt3 = "0.1"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"